### ISSUE TITLE
About the hash

### ISSUE THREAD

**Issue by Jos-Li** [David-vz/MonsterHunterPortable3rdHDRemake#10]
Hello, good day. As stated in texture.ini "#hash = quick or xxh64", I deduced you can only set/choose the hash to either only one between the two, is that right? I'm asking 'cause I don't really know a thing about this repo/code. But, I noticed that when I set it to "hash = quick" under the option, some textures won't work out, like the areas' textures. Here's a sample of the textures they fall under based on my observation;

hash = quick (ANIMATION, MONSTERS, FARM, MAP_ITEMS, ...)
hash = xxh64 (STARTMENU, AREAS, ...)

Both LOADINGSCREEN and MAP texture works fine in quick and xxh64. Now, I would like to know if I could set both at the same time. I tried putting "and" but it doesn't apply. Is there a way? Please let me know. And oh, I don't know a thing about "ignoreAddress = true", so I didn't touch it. It's so nice to see even just the MAP, MONSTERS, and AREAS works fine at the same time. I'm sorry for my bad english. But I'm hoping for your kind and consideration. If only I know how to do like you do sires, I would be glad to help and contribute. Uhm, lastly, I would like to have a request for Yukumo Village. It's grass? stones? whatever it is you walk on to. THANK YOU.

**Comment by Ice-w1nd** [comment]
This texture project was using an old hashing method (quick), so when I contacted @David-vz in order to help him with the project on several areas I told him we should change it to a new, faster and easier to use method (xxh64). The problem is that to change the hashing method you have to also rewrite the textures.ini file entirely, since every texture uses a different hash. He started doing that while I worked on area textures, but it seems he didn't finish updating it, and that's why some textures aren't loading when using the new method. 

He has been super busy with irl stuff during the last month so that's why the project seems on hold. When he comes back we should be able to sort that out.

"ignoreAddress = true" is a feature that the new hashing method implements, and it makes everything so much easier, since it replaces the first 8 characters of the hashes with 0, which helps tremendously when extracting textures from the emulator and heavily prevents the creation of repeated textures.

If you want to help and have free time there are things that are easy to do but again, **require time**; like writing down hashes on the textures.ini file. Tell me if you are interested and I'll teach you.

**Comment by Narugakuruga** [comment]
@Ice-w1nd I want help，but I know nothing about hash. is there a tutorial about how to write hash？

**Comment by Ice-w1nd** [comment]
@realJiangZemin I just wrote a complete tutorial explaining how the whole thing works.
I hope it will help you understand the basics of the system. 

If you have further questions just ask me.

[TextureReplacementTutorial.txt](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2137700/TextureReplacementTutorial.txt)

**Comment by Narugakuruga** [comment]
@Ice-w1nd really thank you，I will learn how to help you guys now

**Comment by Narugakuruga** [comment]
@Ice-w1nd but I still dont understand why some texture dont load and how to make them load. do I need run MHP3rd HD while switch on "save new textures" and find out their hash? the name of the texture file dumped from PSP game is quick hash or 64 hash?( sorry for my bad english)

**Comment by Narugakuruga** [comment]
i noticed the jinouga hash in texture.ini is X64, but in game the jinouga texture doesnt load, why? what can i do to make it load?

**Comment by Ice-w1nd** [comment]
@realJiangZemin I already explained that this project was using the old "quick" hashing method and then we decided to change it to the new one (xxh64). That makes it so we have to extract all textures again using the emulator since the hashes change. David started doing that for some textures (areas for example), but for monsters and other textures we still need to change the hashes with the new ones. 

I actually extracted all monster textures using xxh64, what needs to be done now is replace the old hashes on the textures.ini file with the new ones.

Here are the monster textures, so if you want to do it, just go for it:
https://www.dropbox.com/s/xjuqlykzlhwmti4/p3rd%20monsters.zip?dl=0

**Comment by Narugakuruga** [comment]
@Ice-w1nd OK, i will try. My confusion is when I extracted the monsters texture, I found the file name is the same as the hash in texture.ini

**Comment by Narugakuruga** [comment]
@Ice-w1nd Dropbox is banned in my country and my VPN has some problem now, so I will download them in weekend

**Comment by Narugakuruga** [comment]
@Ice-w1nd Great!! I successfully make zinogre texture load! Now please tell me the hashes of which textures need 
to be rewrited and I can start working on them. By the way , if I have rewrited texture.ini , how to give it to you? I'm sorry I know little about how to use GitHub.

**Comment by Ice-w1nd** [comment]
@realJiangZemin it seems all monster textures need to be replaced with the new hashes. Do you know a website that I can upload the files to so that you can access it from your country? If not then you will have to extract the monster textures with the emulator.

When you have the textures with the new hashes you have to compare them with the hashes in the textures.ini file, if they are different (they should) you need to replace them with the new ones.

You can compress the textures.ini file into a .zip file and upload it in this message like this:
[textures.zip](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2145851/textures.zip)

**Comment by Narugakuruga** [comment]
@Ice-w1nd I Cant upload file on GitHub，even using VPN，so i ll use Google drive。and i ll extract the texture myself

**Comment by Narugakuruga** [comment]
@Ice-w1nd I successfully make all monster texture load except barroth, please help! and I add zinogre's thunder HD texture. Im going to dump more monster texture and add their hash, then I will give all the texture and texture.ini to you

**Comment by Narugakuruga** [comment]
@Ice-w1nd I add gigginox texture and make it load

**Comment by Ice-w1nd** [comment]
@realJiangZemin Perfect! I don't know what the issue with barroth's textures is, but you can skip it and I will check it myself later.

**Comment by Narugakuruga** [comment]
@Ice-w1nd I make rathalos HD texture, but it seems only rathalos wings and head texture load, I will give you the whole texture folder to you. I ll use BAIDU netdisk( a net disk in my country) first, because google is too slow.I ll use google drive later. if baidu is slow in your country , wait for me to upload to google drive

**Comment by Narugakuruga** [comment]
@Ice-w1nd at first，I doubt if it is because the mud on barroth that make the HD texture dont load ，but when I cleaned up all the mud ，the texture still dont load

**Comment by realJiangZemin** [comment]
@Ice-w1nd https://pan.baidu.com/s/1mBV-92GVLqYnj3ZV21d6Zw
you need to sign up baidu account and download the software，if you think it is too trouble， wait for me to upload to Google drive

**Comment by realJiangZemin** [comment]
@Ice-w1nd 注册=sign up 下载=download 保存到网盘=save to my netdisk 客户端下载=software download

**Comment by realJiangZemin** [comment]
@Ice-w1nd you can use my baidu ID
ID：韦添棋
password：weitianq

**Comment by realJiangZemin** [comment]
the texture is in MHP3/NPJB40001.7z

**Comment by Narugakuruga** [comment]
@Ice-w1nd I just fixed the narga's eyes，but the texture is not in the one I give to you

**Comment by Narugakuruga** [comment]
@Ice-w1nd @David-vz https://drive.google.com/file/d/1wrJs9r8yGWsjI6QRtaNuSk5R9yh1iim_/view?usp=drivesdk
Go to see rathalos head and wings、gigiinox、duramboros and the moon and the round bird animation in misty peak！I ve tested all monster except popo. And barroth texture doesn't load

**Comment by Ice-w1nd** [comment]
@realJiangZemin wait. The things you added to Misty Peaks only appear at night, right? Then they would have to go in another folder, to keep things organized. Don't worry about that for now, since we haven't worked on the night version of Misty Peaks yet.

For the monsters now: I see you used textures that you got from mh3uHD right? I already have many of those monster textures done myself, I just have to upload them. So again, please don't worry about that since it's already done.

And for the hashes. It seems there are some things wrong. Every hash has to be in a new line, and the Barroth hashes are all on the same line, I fixed that and other mistakes on that texures.ini file. Barroth should load properly now.

[textures.zip](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2150660/textures.zip)

Still, thank you so much for your work updating the monster hashes!

Though I don't want to continue adding things to the textures.ini file until David comes back, since we have to keep things organized, and he was doing that.

So, if you want to continue helping in the meantime, you could try to get more textures from mh3uHD. I actually got almost all monster textures but there are a few subspecies that I'm missing and it would be great if you could get them:

-Black Diablos
-Green Nargacuga
-Steel Uragaan

**Comment by Narugakuruga** [comment]
@Ice-w1nd what about the rathalos hash? can you fix them?

**Comment by Ice-w1nd** [comment]
@realJiangZemin I think rathalos hashes are correct.

**Comment by Narugakuruga** [comment]
[textures.zip](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2151314/textures.zip)
@Ice-w1nd you just make duramboros and gigiinox texture dont load, and I fixed them, now all the monster textures load properly, except Popo, please check it

**Comment by Narugakuruga** [comment]
@Ice-w1nd I will get the monster textures you need, maybe tomorrow

**Comment by Ice-w1nd** [comment]
@realJiangZemin Oh sorry, I forgot to mention that. I changed the name of the Gigginox texture. You put "Gigiinox", but the correct name is "Gigginox".
I don't know what was wrong with Duramboros, I checked it and it should work.

Regarding Popo, there are some textures, like some small monsters that require that you manually replace everything in the hash with 0, apart from the last 8 digits. For Popo it would be 00000000000000005b22ffe5.

**Comment by realJiangZemin** [comment]
@Ice-w1nd I see. But what about the birds in misty peaks? I got 3 different hashes and one of them makes the bird texture load, but I didn't replace the hash with 0?

**Comment by Narugakuruga** [comment]
[AGGRESSIVE.zip](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2151633/AGGRESSIVE.zip)
[textures.zip](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2151634/textures.zip)
@Ice-w1nd please try out the new HD black diablos and steel uragaan and green narga textures, Ive make them load. (I have some surprise for you ;) )

**Comment by Ice-w1nd** [comment]
@realJiangZemin Thank you so much! Lucent Nargacuga is cool to have as well, though we are not really going to need it, that's why I didn't ask for it, haha.

I see that you adapted them to fit the layouts of the textures in p3rd; thanks for that as well, though I can do that, don't worry. Could you please also send me the original textures from mh3uHD without any modifications? It would be great to have the source textures intact as well.

**Comment by Narugakuruga** [comment]
@Ice-w1nd OK，ill give you the original texture. By the way，i have a software that can extract files from Nintendo Switch games, and I can extract the opening and monsters movies from MHXX NS, so I wonder if its possible to get HD tigrex texture using this software?(I don't find any BMP or PNG files in the game ,most of the files are .arc format)

**Comment by Ice-w1nd** [comment]
@realJiangZemin Ohh, that's AMAZING! I tried doing that several months ago but I couldn't find anything.

If the .arc files work similarly to the 3ds version I think we might be able to make them work.

**Comment by Jos-Li** [comment]
Thank you icewind and realjiang for responding to my post, I really appreciated it. I couldn't really get what you two guys are saying, but thank you for sharing some files. I'll download it later. I don't have a personal computer, and I'm using ppsspp on android. I just copied the TEXTURE folder into PSP folder, and that's it. I think, the graphics is more enhanced in android than in PC, since it minimizes? Uhm, to be exact, the graphics looks way better when played on android 'cause the screen is smaller? Am I right? But still when you look on the radius of the ground where your character standing to, you can fairly see it's somehow pixelated. That's exactly the sole reason why I got here in github, repo thingy. Yeah, searching for a remedy for it. 'Cause it's bugging me. You know the feeling? The area is so dry... But, I wanted to know if Yukumo Village could be retexturize? The farm, home, and guild hall are already good. But the village's ground, grass, stones (what you step on to) I find it somehow dry. I wanted, I'll try, I guess? To work Yukumo out. But how to extract the images and replace it with an hd ones? Do I need to use a photoshop or search for closely resembled the images out of it? I'm sorry, I'm just a regular gamer though. But, again I'll be rooting for this repo, hoping for its great progress. Keep up the good work guys. THANK YOU.

**Comment by Jos-Li** [comment]
Guys, I just did something I thought I could never do. Well, I read icewind's replacement tutorial, and somehow I get it. First, I backuped the original TEXTURE file (moved somewhere) and then created a new one with a sub folder NJB... and a clean texture.ini in it. I followed the instruction; touched the save texture file while running the mhp3rd, and yes after I run abouts in Yukumo Village. I went to the files, and saw the "new" folder with bunches of images with code like names? So, I think I get it now. My problems' are. First, I can't find the ground, grass, stones. I mean, the tileset you step on to in Yukumo. Second, how do I enhance it to HD? Is there a one-click-app photo hd editor? Or do I need photoshop? But I don't have any background using the photoshop. So, help me. Help me exclude the unecessary images I extracted. I uploaded it: https://drive.google.com/file/d/1JdntWvsbqx2Kc-0ECTkB4CgVM8Y6tSiB/view?usp=drivesdk

I'd be glad to work with Yukumo Village.

**Comment by Narugakuruga** [comment]
@Wakoko actually someone had replaced yukumo village textures before，using other textures（because yukumo village only appear in MHP3, MHP3 HD, MHGen MHXX MHXX NS，and we cant extract MHXX NS texture for now），and the HD textures look unnatural.  as for the problem you meet, there is one situation fits your problem, if the original texture had already been replaced (like the loading screen) ,the original texture wont be extracted

**Comment by Narugakuruga** [comment]
[new.zip](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2158395/new.zip)
@Wakoko I extracted some yukumo village stones and grass texture, check them( sorry I cant download files from google drive)

**Comment by Narugakuruga** [comment]
@Wakoko To upscale the original texture，you can use a software called waifu2x-caffe，here are some examples. compare them with the original ones
[00000000de7e13deefb6d31b multi(UpPhoto)(scale)(x2.000000).zip](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2158416/00000000de7e13deefb6d31b.multi.UpPhoto.scale.x2.000000.zip)
or， we need a Photoshop expert to manually upscale them

**Comment by Jos-Li** [comment]
Thank you, realJiang. I got it. Uhm, I think, you miss the patches of stones, the white ones with black edges, the ones on the ground? I'm looking for it. And I noticed with what you've sent, the images were just sharpened. But I'll try it anyways to sew if it will look good. Thank you once again, sir.

**Comment by Narugakuruga** [comment]
@Wakoko please give me a screenshot of that stone in the game

**Comment by Narugakuruga** [comment]
![0000000066c5af969cad0c77](https://user-images.githubusercontent.com/31060534/42211514-67413c80-7ee6-11e8-9ee4-2d6fe5173f62.png)
this one?

**Comment by Jos-Li** [comment]
Oh, I almost. Could you send your latest MONSTERS folder? The one you've sent only contains the subspecies. I saw you were talking with icewind about los, duram, giggi, and others. And lastly, I saw you mentioned baidu? I guess, you're chinese, yes? Well, could you do me a little favor? I'm currently searching for a save file that contains complete/almost the special downloaded cats. I tried in jap google, but google translation s*cks, can't find one. I tried in google hk too, still the same, couldn't find one.

**Comment by Jos-Li** [comment]
Yes, that's one. My friend.

**Comment by Jos-Li** [comment]
Could you include that stone too? That's what I'm searching.

**Comment by Narugakuruga** [comment]
@Wakoko do you have discord?

**Comment by Jos-Li** [comment]
What's a discord?

**Comment by Narugakuruga** [comment]
@Wakoko yes im chinese, so I cant use google drive now because my VPN has some problem. I dont know if i can upload big files on github. discord is like whatsapp, it allow you to chat and send files to friends

**Comment by Jos-Li** [comment]
Send me the image of that stone my friend with its code like name. Thank you. I'll try working on yukumo.

**Comment by Jos-Li** [comment]
A moment, ill try making account

**Comment by Narugakuruga** [comment]
[0000000066c5af969cad0c77.zip](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2158631/0000000066c5af969cad0c77.zip)
@Wakoko

**Comment by Narugakuruga** [comment]
@Wakoko my discord :wei (#0384)

**Comment by Narugakuruga** [comment]
@Wakoko I have an cat cheats code generator which allow you to edit the cats，you can edit the common cats into downloaded cats

**Comment by Jos-Li** [comment]
It says, "didn't work check capitalization, spelling, spaces, ..." When I'm adding you. Let's talk about that cats in discord, hihi.

**Comment by Narugakuruga** [comment]
@Wakoko I dont receive your request

**Comment by Narugakuruga** [comment]
@Wakoko tell me your discord ID

**Comment by Jos-Li** [comment]
I tried, and tried adding you. Uhm, #8702

**Comment by Jos-Li** [comment]
Still same name, Wakoko

**Comment by Wakoko** [comment]
@Ice-w1nd @Narugakuruga @David-vz 

![project_yukumo](https://user-images.githubusercontent.com/40482773/42418825-2a28680c-82db-11e8-9bd3-d392784280df.png)

I'm just renting in a net cafe for this. Since, I do have a little knowledge about this repo thingy now, thanks to icewind. I tried Yukumo Village. As you can see, I'm not even halfway there. Only the sky, distance mountains, and the ground that I've retouched yet. But I got frustrated, I can't find an appropriate texture replacement. I'd be glad if you lend me some help or texture files for Yukumo Village (from PS3?) or from any other source. I just need some grasses, stone steps (ground), and stone steps (stair). And it will be good to go. Aside from retexturizing Yukumo, I've done some few retouching too and fixed some hashes. Like, the chests, the bug seesaw, and etc. I disclosed a file regarding it, just the added ones. So please, have take a look, and read the "README" first. I'm hoping david and you guys will notice this. And I can work with armors and weapons too, if you want, just send me a link or upload the hd textures for weapons and armors. Thank you, happy playing.

[http://www.mediafire.com/file/gi7bo5r3o1byjja/retouch.zip](url)

**Comment by Wakoko** [comment]
http://www.mediafire.com/file/gi7bo5r3o1byjja/retouch.zip

**Comment by Jos-Li** [comment]
@David-vz @Ice-w1nd @Narugakuruga 

![project_yukumo](https://user-images.githubusercontent.com/40482773/42419257-7aac91a6-82e3-11e8-87c3-7560168b44e2.png)

I'm just renting in a net cafe for this. Since, I do have a little knowledge about this repo thingy now, thanks to icewind. I tried Yukumo Village. As you can see, I'm not even halfway there. Only the sky, distance mountains, and the ground that I've retouched yet. But I got frustrated, I can't find an appropriate texture replacement. I'd be glad if you lend me some help or texture files for Yukumo Village (from PS3?) or from any other source. I just need some grasses, stone steps (ground), and stone steps (stair). And it will be good to go. Aside from retexturizing Yukumo, I've done some few retouching too and fixed some hashes. Like, the chests, the bug seesaw, and etc. I disclosed a file regarding it, just the added ones. So please, have take a look, and read the "README" first. I'm hoping david and you guys will notice this. And I can work with armors and weapons too, if you want, just send me a link or upload the hd textures for weapons and armors. Thank you, happy playing.

http://www.mediafire.com/file/gi7bo5r3o1byjja/retouch.zip/file

**Comment by Narugakuruga** [comment]
@Wakoko Great works! You've worked hard! Firstly the game we are remaking is Monster Hunter Portable 3rd HD. Ver from PS3. CAPCOM upscaled some textures(like yukumo village and most monsters ) in Monster Hunter Portable 3rd, a PSP game. Then they packed it into a PS3 game which can be run by the PSP Remaster emulator on PS3. That game is MHP3rd HD. So the yukumo village textures you have are the HD textures from PS3. They are more HD than those in MHGen. And I already said we can't get MHGU textures for now.  And about the weapons and armors textures, those textures in MH3U HD I think are the same resolution with MHP3rd HD. But I think MHXX's armors textures looks a bit more clear,  maybe I can get them for you. 😃

**Comment by Ice-w1nd** [comment]
@Wakoko Wow, that's really cool! 
After many days trying I finally managed to get the textures from MHGU (the NSwitch version of MHXX). So now there are a lot of things that we will be able to do. For starters, we can get the new textures from Yokumo Village and see what we can use from there. And then we can also get monster textures, and more. The process to getting those textures is kinda annoying but if you want I can teach you how to do it.

**Comment by Narugakuruga** [comment]
@Ice-w1nd what？？you get mhgu textures???? How can you do that ?(sorry I cant use discord now )

**Comment by game456a** [comment]
Ah guys i added Uragaan, Deviljho, Purple Ludroth, Alatreon, Jhen Mohran, Baleful Gigginox, ICE Barroth and 2 armores textures. Those textures from MH3U  but i didnt edit
[NPJB40001.zip](https://github.com/David-vz/MonsterHunterPortable3rdHDRemake/files/2175685/NPJB40001.zip)

**Comment by game456a** [comment]
@Narugakuruga yeah i will join and dont worry i had PC and photoshop. Lets me help you guys
