### ISSUE TITLE
deserted island and item texture doesn't load

### ISSUE THREAD

**Issue by Narugakuruga** [David-vz/MonsterHunterPortable3rdHDRemake#8]
![ppsspp v1 5 4-993-gab65c5210 - npjb40001 _ monster hunter portable 3rd hd ver 2018_5_22 10_44_31](https://user-images.githubusercontent.com/31060534/40339468-2be3cd74-5dad-11e8-80f7-1b3c2c0dea7c.png)
but the sandy plains texture loads properly.
my ppsspp version is 1.5.4-993 x64
by the way really thank you for your amazing work i wonder if i can contribute to your project

**Comment by David-vz** [comment]
Hey realJiangZemin.
Good catch! 

Yes some textures won't load for a short while. Completely redoing the hash format from the old style to the faster x64 style. 

Have been converting these since last saturday but its still got a way to go. Check back often this coming week, updates should come quickly.

Any help is appreciated. Its a big and time consuming project. Let me know if and how you want to contribute and I'll help run you through any of the technical stuff

**Comment by David-vz** [comment]
@realJiangZemin , try the current build. Deserted Island should work as expected :)

**Comment by Narugakuruga** [comment]
@David-vz ,deserted Island works now.

**Comment by Narugakuruga** [comment]
I have Wii U emulator and MH3U HD, and it can dump game texture. can I help you dump texture? @David-vz

**Comment by Ice-w1nd** [comment]
@realJiangZemin Yes! That would be really useful. I already extracted all areas' textures from MHTri, but on MH3U HD there are some that can't be found on Tri. I extracted some from MH3U HD as well but my pc has serious problems running the Wii U emulator, so that's really annoying to do for me. Getting textures from the Tundra, Volcano and Flooded Forest is the priority. David is working on the Flooded Forest at the moment and I almost finished with the Tundra using MHTri textures (but I'm curious if there are some different textures in MH3U). If you have any questions about how to dump the textures just ask. The only annoying thing is that the Wii U emulator creates multiple copies of the same textures for the mipmaps, so you have to manually select only 1 of each (the one with the largest size).

**Comment by Narugakuruga** [comment]
@Ice-w1nd I extracted volcano texture, but i don't know how to give it to you

**Comment by Narugakuruga** [comment]
@Ice-w1nd https://drive.google.com/file/d/1PPQHfSYjbyUCads6WDScqZycyzTC_KWB/view?usp=drivesdk

**Comment by Ice-w1nd** [comment]
@realJiangZemin Wow! Thanks a lot! I may start working on the Volcano once I finish the Tundra.

**Comment by Narugakuruga** [comment]
@Ice-w1nd 
I dumped all the tundra night texture
https://drive.google.com/file/d/1Gg6ag3v4w58S6bomvmgEHU-gxs2-3lkv/view?usp=drivesdk

**Comment by Ice-w1nd** [comment]
@realJiangZemin oh thank you, but the Tundra is already done. Haven't you tried the improved textures I did?

**Comment by Narugakuruga** [comment]
@Ice-w1nd yes I tried，but i notice the night tundra dont have area 8 texture。is it because the day and night are the same？

**Comment by Ice-w1nd** [comment]
@realJiangZemin yes, many textures are the same during day and night, that's why if you look at the folders you will see less files in the night one. In-game every texture should load properly. If you find one that doesn't load, please tell us.

Either way, I just looked at the MH3U textures you just shared and I realized that there's 1 texture there that's higher quality than the one used in MHTri, so I'm gonna replace it.
